### ISSUE TITLE
ModuleNotFoundError: No module named 'mumc_config'

### ISSUE THREAD

**Issue by mk89pwnz** [terrelsa13/media_cleaner#103]
```
Decide how to select users and/or libraries.
0 - Select users and libraries.
    Select specific users and the specific libraries to be blacklisted for each user.
1 - Select users only.
    Selected users will have all libraries blacklisted according to their access policy.
2 - Select libraries only.
    Selected libraries will be blacklisted for all users according to their access policy.
Enter number (default 0 - Select users and libraries): 0
----------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/MUMC/mumc_modules/mumc_config_import.py", line 90, in importConfig
    import mumc_config as cfg
ModuleNotFoundError: No module named 'mumc_config'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/MUMC/mumc.py", line 110, in <module>
    MUMC()
  File "/data/MUMC/mumc.py", line 28, in MUMC
    cfg,init_dict=importConfig(init_dict,cmdopt_dict)
  File "/data/MUMC/mumc_modules/mumc_config_import.py", line 106, in importConfig
    importHasException(init_dict,cmdopt_dict)
  File "/data/MUMC/mumc_modules/mumc_config_import.py", line 21, in importHasException
    build_configuration_file(init_dict)
  File "/data/MUMC/mumc_modules/mumc_config_builder.py", line 137, in build_configuration_file
    the_dict['admin_settings']['users']=get_users_and_libraries(the_dict)
  File "/data/MUMC/mumc_modules/mumc_builder_userlibrary.py", line 38, in get_users_and_libraries
    the_dict=update_existing_user_libraries(the_dict)
  File "/data/MUMC/mumc_modules/mumc_builder_library.py", line 80, in update_existing_user_libraries
    opposing_listing_type=get_opposing_listing_type(he_dict['admin_settings']['behavior']['list'])
NameError: name 'he_dict' is not defined
```
Using latest version, don't get why I'm getting this :(

**Comment by mk89pwnz** [comment]
downloaded dev branch version then needed to create mumc_config.yaml manually and now its working. Tried it on master branch but it still gives this error even when creating the mumc_config.yaml file manually.

**Comment by terrelsa13** [comment]
@mk89pwnz 

This is my fault. Looks like a typo.

```NameError: name 'he_dict' is not defined```

The ```he_dict``` should be ```the_dict```. I will fix this as soon as I get a chance.

**Comment by terrelsa13** [comment]
I have corrected my copy/paste errors in the latest version [v5.6.4](https://github.com/terrelsa13/MUMC/releases).

Apologies for the confusion.
