### ISSUE TITLE
Fails to install Dependencies on Ubuntu 22.04

### ISSUE THREAD

**Issue by Doug411** [terrelsa13/media_cleaner#108]
I get the following error when installing dependencies on Ubuntu 22.04.

Also is there instructions on how to run this with docker? I downwloaded the docker image, and searched through the Wiki and old issues, but wasnt able to find anything other than modification requests.

`d /opt/MUMC && pip3 install -r requirements.txt
Defaulting to user installation because normal site-packages is not writeable
Collecting emoji==2.8.0
Downloading emoji-2.8.0-py2.py3-none-any.whl (358 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 358.9/358.9 KB 6.1 MB/s eta 0:00:00
Collecting python-dateutil==2.8.2
Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 247.7/247.7 KB 9.2 MB/s eta 0:00:00
Collecting PyYAML==5.4.1
Downloading PyYAML-5.4.1.tar.gz (175 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 175.1/175.1 KB 10.7 MB/s eta 0:00:00
Installing build dependencies ... done
Getting requirements to build wheel ... error
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> [43 lines of output]
running egg_info
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in
main()
File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
json_out['return_val'] = hook(**hook_input['kwargs'])
File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
return hook(config_settings)
File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 162, in get_requires_for_build_wheel
return self._get_build_requires(
File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 143, in _get_build_requires
self.run_setup()
File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 158, in run_setup
exec(compile(code, file, 'exec'), locals())
File "setup.py", line 271, in
setup(
File "/usr/lib/python3/dist-packages/setuptools/init.py", line 153, in setup
return distutils.core.setup(**attrs)
File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 148, in setup
return run_commands(dist)
File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 163, in run_commands
dist.run_commands()
File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 967, in run_commands
self.run_command(cmd)
File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 986, in run_command
cmd_obj.run()
File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 299, in run
self.find_sources()
File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 306, in find_sources
mm.run()
File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 541, in run
self.add_defaults()
File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 578, in add_defaults
sdist.add_defaults(self)
File "/usr/lib/python3/dist-packages/setuptools/_distutils/command/sdist.py", line 228, in add_defaults
self._add_defaults_ext()
File "/usr/lib/python3/dist-packages/setuptools/_distutils/command/sdist.py", line 312, in _add_defaults_ext
self.filelist.extend(build_ext.get_source_files())
File "setup.py", line 201, in get_source_files
self.cython_sources(ext.sources, ext)
File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 103, in getattr
raise AttributeError(attr)
AttributeError: cython_sources
[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.`

**Comment by terrelsa13** [comment]
@Doug411 Apologies. I never finished making the updates needed for the containerized MUMC to run properly. That is no longer the case. For now the updates are on the ```MUMC_dev``` branch. Do not pull the latest branch, instead pull from the dev branch. Only the latest beta release will allow setting up a config file within the container. You should not need to manually pip install any python packages on the host machine now.

~~```ghcr.io/terrelsa13/mumc:latest``` - The latest stable release.~~
```ghcr.io/terrelsa13/mumc:MUMC_dev``` - The latest beta release.

The [install instructions for Docker](https://github.com/terrelsa13/MUMC/wiki/Install#Docker) have been updated. Let me know if you have any issues.

Once I am comfortable I have not made any obvious errors in the MUMC_dev branch; those changes will be pushed to the MUMC-Latest branch. Once that happens mumc:latest will work without having to build the config outside of the container.

**Comment by Doug411** [comment]
Thanks.! FYI.  I think the problem was the PyYAML==5.4.1 dependency.  I already had 6.0.   I changed the requirements file to 6.0 and reran the build. It indicated all dependencies had been met.   It seemed to run after that.

I will post another issue related to functionality.  I'm probably not understanding it.

Thanks again for the prompt response.   Once I get the functionality working the way I want, I'll give the docker install a whirl and let you know how it goes.
