### ISSUE TITLE
Issues with script

### ISSUE THREAD

**Issue by zilexa** [terrelsa13/media_cleaner#24]
On a fresh system, I downloaded both files (I cannot execute without the defaults file), but I cannot login: 

This is using jellyfin on the same system so I just hit Enter on all initial questions (to accept the defaults). Then enter my username and password. Result is this:

```
An error occured, a maximum of 3 attempts met, and no data retrieved from the "get_authentication_key" lookup.
Traceback (most recent call last):
  File "/home/asterix/docker/HOST/mediacleaner/./media_cleaner.py", line 5992, in <module>
    import media_cleaner_config as cfg
ModuleNotFoundError: No module named 'media_cleaner_config'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/asterix/docker/HOST/mediacleaner/./media_cleaner.py", line 6011, in <module>
    generate_edit_config(None,update_config)
  File "/home/asterix/docker/HOST/mediacleaner/./media_cleaner.py", line 1038, in generate_edit_config
    auth_key=get_authentication_key(server_url, username, password, server_brand)
  File "/home/asterix/docker/HOST/mediacleaner/./media_cleaner.py", line 398, in get_authentication_key
    return(data['AccessToken'])
TypeError: 'JSONDecodeError' object is not subscriptable

```

**Comment by zilexa** [comment]
OK when I enter my host IP address (this script runs on host, I am used to it working with the default localhost), I can do the initial run. 

But the actual run to delete files doesn't return anything to delete.. It should have 50+ episodes to delete and a movie: 
```
python3 ./media_cleaner.py                                                                                           ✔ 
-----------------------------------------------------------



-----------------------------------------------------------
Script Verion: 2.1.1
-----------------------------------------------------------
Start...
Cleaning media for server at: http://192.168.88.2:8096/emby
-----------------------------------------------------------


-----------------------------------------------------------
Get List Of Media For:
asterix - 6c822a4b798d488d8f3950bac2385494
-----------------------------------------------------------
[NO PLAYED ITEMS]
-----------------------------------------------------------


-----------------------------------------------------------
Summary Of Deleted Media:
* Items Deleted = 0    *
-----------------------------------------------------------
[NO ITEMS TO DELETE]
-----------------------------------------------------------


-----------------------------------------------------------
Done.
-----------------------------------------------------------

```

Nevermind.. I had to select my libraries during first run, when asked which libraries to _blacklist_.

It's great you added many features but this part is quite counter-intuitive.
