### ISSUE TITLE
Error in Summary Of Deleted Media

### ISSUE THREAD

**Issue by keppo070** [terrelsa13/media_cleaner#57]
Got errors in the summary. About 160 of them

Deleting is ok. Occurs only when I have REMOVE_FILES=True.  When running same script with REMOVE_FILES=False then there are no errors.

I reverted back to the 'old' version.

(Great to see how this script has evolved from v1 👍)

```
MUMC Version: 3.3.2
Emby Version: 4.7.11.0
Python Version: 3.9.2
Time Stamp: 20221222210001
```

```
-----------------------------------------------------------
Summary Of Deleted Media:
* Items Deleted = 160    *
-----------------------------------------------------------

generic exception: Traceback (most recent call last):
  File "/home/patrick/programmeren/python/mumc3/mumc.py", line 352, in requestURL
    GLOBAL_CACHED_DATA.saveEntryToCache(url,data)
  File "/home/patrick/programmeren/python/mumc3/mumc.py", line 282, in saveEntryToCache
    newDataSize=self.getDataSize(url) + self.getDataSize(data) + self.getDataSize(self.getNewestCachedDataEntry() + 1)
  File "/home/patrick/programmeren/python/mumc3/mumc.py", line 256, in getDataSize
    size+=(obj.__dict__, seen)
TypeError: unsupported operand type(s) for +=: 'int' and 'tuple'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/patrick/programmeren/python/mumc3/mumc.py", line 7381, in delete_media_item
    requestURL(req, GLOBAL_DEBUG, 'delete_media_item_request', 3)
  File "/home/patrick/programmeren/python/mumc3/mumc.py", line 362, in requestURL
    if (err.msg == 'Unauthorized'):
AttributeError: 'TypeError' object has no attribute 'msg'

[DELETED]     Movie - filename - 12345
```

**Comment by terrelsa13** [comment]
Much appreciated. This is an error that is being thrown because the cache is trying to handle 'DELETE' and 'POST' methods. Cache was meant to only handle 'GET' methods. I am not able to push the fix to trunk right now (something going on on my end most likely). But I will as soon as VSCode and GitHub are playing together nicely.

**Comment by terrelsa13** [comment]
FYI - v3.3.4 has been pushed to the trunk.
