### ISSUE TITLE
Error in advanced favorite config

### ISSUE THREAD

**Issue by keppo070** [terrelsa13/media_cleaner#63]
```
favorited_behavior_movie=['keep', 'any', 'ignore', 3]
```

What I am trying to accomplish is that any user who has a favorite movie is not deleted. No matter the played state. 

But I get the following error message. (maybe I'm mis interpreting the config option)

```
-----------------------------------------------------------
MUMC Version: 4.0.6-beta
Emby Version: 4.7.11.0
Python Version: 3.9.2
Time Stamp: 20230109100852
-----------------------------------------------------------

Traceback (most recent call last):
  File "/home/patrick/programmeren/python/MUMC-MUMC_v4-BETA/mumc.py", line 9693, in <module>
    cfgCheck()
  File "/home/patrick/programmeren/python/MUMC-MUMC_v4-BETA/mumc.py", line 9527, in cfgCheck
    raise RuntimeError('\n' + error_found_in_mumc_config_py)
RuntimeError: 
ConfigValueError: favorited_behavior_movie must be a list with four entries
        Valid values for first entry 'delete' and 'keep'
        Valid values for second and third entry 'all', 'any', and 'ignore'
        Valid range for fourth entry 0 thru 8
```

**Comment by terrelsa13** [comment]
@keppo070 Typo in config checker. Should be fixed now on [v4 branch](https://github.com/terrelsa13/MUMC/tree/MUMC_v4-BETA) with v4.0.7-beta.

**Comment by keppo070** [comment]
```
-----------------------------------------------------------

-----------------------------------------------------------
MUMC Version: 4.0.11-beta
Emby Version: 4.7.11.0
Python Version: 3.9.2
Time Stamp: 20230111163413
-----------------------------------------------------------

Traceback (most recent call last):
  File "/home/patrick/programmeren/python/MUMC-MUMC_v4-BETA/mumc.py", line 9810, in <module>
    cfgCheck()
  File "/home/patrick/programmeren/python/MUMC-MUMC_v4-BETA/mumc.py", line 9644, in cfgCheck
    raise RuntimeError('\n' + error_found_in_mumc_config_py)
RuntimeError:
ConfigValueError: favorited_behavior_episode must be a list with four entries
        Valid values for first entry 'delete' and 'keep'
        Valid values for second and third entry 'all', 'any', and/or 'ignore'
        Valid range for fourth entry 0 thru 8
ConfigValueError: favorited_behavior_audio must be a list with four entries
        Valid values for first entry 'delete' and 'keep'
        Valid values for second and third entry 'all', 'any', and/or 'ignore'
        Valid range for fourth entry 0 thru 8
ConfigValueError: whitetagged_behavior_movie must be a list with four entries
        Valid values for first entry 'delete' and 'keep'
        Valid values for second and third entry 'all' and 'ignore'
        Valid range for fourth entry 0 thru 8
ConfigValueError: whitetagged_behavior_episode must be a list with four entries
        Valid values for first entry 'delete' and 'keep'
        Valid values for second and third entry 'all' and 'ignore'
        Valid range for fourth entry 0 thru 8
ConfigValueError: whitetagged_behavior_audio must be a list with four entries
        Valid values for first entry 'delete' and 'keep'
        Valid values for second and third entry 'all' and 'ignore'
        Valid range for fourth entry 0 thru 8
ConfigValueError: whitelisted_behavior_movie must be a list with four entries
        Valid values for first entry 'delete' and 'keep'
        Valid values for second and third entry 'all', 'any', and/or 'ignore'
        Valid range for fourth entry 0 thru 8
ConfigValueError: whitelisted_behavior_episode must be a list with four entries
        Valid values for first entry 'delete' and 'keep'
        Valid values for second and third entry 'all', 'any', and/or 'ignore'
        Valid range for fourth entry 0 thru 8
ConfigValueError: whitelisted_behavior_audio must be a list with four entries
        Valid values for first entry 'delete' and 'keep'
        Valid values for second and third entry 'all', 'any', and/or 'ignore'
        Valid range for fourth entry 0 thru 8

```
