### ISSUE TITLE
Error in config

### ISSUE THREAD

**Issue by keppo070** [terrelsa13/media_cleaner#64]
maybe related to https://github.com/terrelsa13/MUMC/issues/63#issue-1525206828

```
-----------------------------------------------------------

-----------------------------------------------------------
MUMC Version: 4.0.11-beta
Emby Version: 4.7.11.0
Python Version: 3.9.2
Time Stamp: 20230111163413
-----------------------------------------------------------

Traceback (most recent call last):
  File "/home/patrick/programmeren/python/MUMC-MUMC_v4-BETA/mumc.py", line 9810, in <module>
    cfgCheck()
  File "/home/patrick/programmeren/python/MUMC-MUMC_v4-BETA/mumc.py", line 9644, in cfgCheck
    raise RuntimeError('\n' + error_found_in_mumc_config_py)
RuntimeError:
ConfigValueError: favorited_behavior_episode must be a list with four entries
        Valid values for first entry 'delete' and 'keep'
        Valid values for second and third entry 'all', 'any', and/or 'ignore'
        Valid range for fourth entry 0 thru 8
ConfigValueError: favorited_behavior_audio must be a list with four entries
        Valid values for first entry 'delete' and 'keep'
        Valid values for second and third entry 'all', 'any', and/or 'ignore'
        Valid range for fourth entry 0 thru 8
ConfigValueError: whitetagged_behavior_movie must be a list with four entries
        Valid values for first entry 'delete' and 'keep'
        Valid values for second and third entry 'all' and 'ignore'
        Valid range for fourth entry 0 thru 8
ConfigValueError: whitetagged_behavior_episode must be a list with four entries
        Valid values for first entry 'delete' and 'keep'
        Valid values for second and third entry 'all' and 'ignore'
        Valid range for fourth entry 0 thru 8
ConfigValueError: whitetagged_behavior_audio must be a list with four entries
        Valid values for first entry 'delete' and 'keep'
        Valid values for second and third entry 'all' and 'ignore'
        Valid range for fourth entry 0 thru 8
ConfigValueError: whitelisted_behavior_movie must be a list with four entries
        Valid values for first entry 'delete' and 'keep'
        Valid values for second and third entry 'all', 'any', and/or 'ignore'
        Valid range for fourth entry 0 thru 8
ConfigValueError: whitelisted_behavior_episode must be a list with four entries
        Valid values for first entry 'delete' and 'keep'
        Valid values for second and third entry 'all', 'any', and/or 'ignore'
        Valid range for fourth entry 0 thru 8
ConfigValueError: whitelisted_behavior_audio must be a list with four entries
        Valid values for first entry 'delete' and 'keep'
        Valid values for second and third entry 'all', 'any', and/or 'ignore'
        Valid range for fourth entry 0 thru 8
```

**Comment by terrelsa13** [comment]
It is.
Updates pushed to [v4 branch](https://github.com/terrelsa13/MUMC/tree/MUMC_v4-BETA). Give v4.0.12-beta a try.

**Comment by terrelsa13** [comment]
FYI - The second list entry can no longer be ```ignore```. It has to be ```all``` or ```any``` or just ```all``` if whitetag/blacktag.

**Comment by keppo070** [comment]
Maybe there is something else wrong. I only updated the mumc.py and the readme.md

Do I need to recreate the mumc_config.py

```
-----------------------------------------------------------

-----------------------------------------------------------
MUMC Version: 4.0.13-beta
Emby Version: 4.7.11.0
Python Version: 3.9.2
Time Stamp: 20230114142506
-----------------------------------------------------------

Traceback (most recent call last):
  File "/home/patrick/programmeren/python/MUMC-MUMC_v4-BETA/mumc.py", line 9844, in <module>
    cfgCheck()
  File "/home/patrick/programmeren/python/MUMC-MUMC_v4-BETA/mumc.py", line 9678, in cfgCheck
    raise RuntimeError('\n' + error_found_in_mumc_config_py)
RuntimeError:
ConfigValueError: whitetagged_behavior_movie must be a list with four entries
        Valid values for first entry 'delete' and 'keep'
        Valid values for second and third entry 'all' and 'ignore'
        Valid range for fourth entry 0 thru 8
ConfigValueError: whitetagged_behavior_episode must be a list with four entries
        Valid values for first entry 'delete' and 'keep'
        Valid values for second and third entry 'all' and 'ignore'
        Valid range for fourth entry 0 thru 8
ConfigValueError: whitetagged_behavior_audio must be a list with four entries
        Valid values for first entry 'delete' and 'keep'
        Valid values for second and third entry 'all' and 'ignore'
        Valid range for fourth entry 0 thru 8
ConfigValueError: whitelisted_behavior_movie must be a list with four entries
        Valid values for first entry 'delete' and 'keep'
        Valid values for second and third entry 'all', 'any', and/or 'ignore'
        Valid range for fourth entry 0 thru 8
ConfigValueError: whitelisted_behavior_episode must be a list with four entries
        Valid values for first entry 'delete' and 'keep'
        Valid values for second and third entry 'all', 'any', and/or 'ignore'
        Valid range for fourth entry 0 thru 8
ConfigValueError: whitelisted_behavior_audio must be a list with four entries
        Valid values for first entry 'delete' and 'keep'
        Valid values for second and third entry 'all', 'any', and/or 'ignore'
        Valid range for fourth entry 0 thru 8

```

**Comment by terrelsa13** [comment]
Shouldn't have needed to. But maybe I messed something up. Let me know if building the config doesn't fix the issue

**Comment by keppo070** [comment]
fixed after building a config. Not sure, about my mistake.
