### ISSUE TITLE
Error when creating mumc_config.py

### ISSUE THREAD

**Issue by keppo070** [terrelsa13/media_cleaner#65]
Version: 4.1.3-beta

I ran the latetest release with my old mumc_config.py and got the following result

```
Traceback (most recent call last):
  File "/home/patrick/programmeren/python/MUMC-MUMC_v4-BETA/mumc.py", line 8403, in <module>
    config_dict=cfgCheck()
  File "/home/patrick/programmeren/python/MUMC-MUMC_v4-BETA/mumc.py", line 8247, in cfgCheck
    raise RuntimeError('\n' + error_found_in_mumc_config_py)
RuntimeError:
ConfigValueError: movie_set_missing_last_played_date must be a boolean; valid values True and False
ConfigValueError: episode_set_missing_last_played_date must be a boolean; valid values True and False
ConfigValueError: audio_set_missing_last_played_date must be a boolean; valid values True and False

```

Then I tried to create a new (not by updating) mumc_config.py and I got the following error

```
Traceback (most recent call last):
  File "/home/patrick/programmeren/python/MUMC-MUMC_v4-BETA/mumc.py", line 8316, in <module>
    import mumc_config as cfg
ModuleNotFoundError: No module named 'mumc_config'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/patrick/programmeren/python/MUMC-MUMC_v4-BETA/mumc.py", line 8395, in <module>
    build_configuration_file(None,update_config)
  File "/home/patrick/programmeren/python/MUMC-MUMC_v4-BETA/mumc.py", line 1461, in build_configuration_file
    auth_key=get_authentication_key(server_url, username, password)
  File "/home/patrick/programmeren/python/MUMC-MUMC_v4-BETA/mumc.py", line 789, in get_authentication_key
    data=requestURL(req, preConfigDebug, 'get_authentication_key', 3)
  File "/home/patrick/programmeren/python/MUMC-MUMC_v4-BETA/mumc.py", line 451, in requestURL
    data = GLOBAL_CACHED_DATA.getCachedDataFromURL(url)
NameError: name 'GLOBAL_CACHED_DATA' is not defined
```

**Comment by terrelsa13** [comment]
Looks like your old config works. Just needed to change the ```*_set_missing_last_played_date``` options from ```0/1``` to ```True/False```.

I will be able to take a look at why a new config won't build a little later. Looks like I have gotten something out of order.

**Comment by keppo070** [comment]
Changed the ```1``` to ```True``` in ```*_set_missing_last_played_date``` got the following error

```
Traceback (most recent call last):
  File "/home/patrick/programmeren/python/MUMC-MUMC_v4-BETA/mumc.py", line 8527, in <module>
    episode_dict,episode_found=get_media_items('episode',config_dict,episode_dict,user_key)
  File "/home/patrick/programmeren/python/MUMC-MUMC_v4-BETA/mumc.py", line 5808, in get_media_items
    =get_playedCreatedDays_playedCreatedCounts(item,media_played_days,media_created_days,cut_off_date_played_media,cut_off_date_created_media,
  File "/home/patrick/programmeren/python/MUMC-MUMC_v4-BETA/mumc.py", line 4310, in get_playedCreatedDays_playedCreatedCounts
    if ((cut_off_date_played) > (parse(item['UserData']['LastPlayedDate']))):
  File "/usr/local/lib/python3.9/dist-packages/dateutil/parser/_parser.py", line 1368, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/dateutil/parser/_parser.py", line 643, in parse
    raise ParserError("Unknown string format: %s", timestr)
dateutil.parser._parser.ParserError: Unknown string format: Unplayed

```

**Comment by terrelsa13** [comment]
The issue with the new config not being built correctly has been [fixed](https://github.com/terrelsa13/MUMC/tree/MUMC_v4-BETA). ```v4.1.14-beta```

The other issue, I am having some trouble understanding how this is happening.
You have an item that has been played at least once; but has no ```LastPlayedDate```.

If the error is still happening after trying ```v4.1.14-beta```; please set ```DEBUG=4```. Run the script. Attach ```mumc_DEBUG.log``` and reply. This will allow me to see what/why this item is and figure out a way to handle it in the script.

**Comment by keppo070** [comment]
i am not sure where to retrieve the latest beta. I tried the following URL

https://github.com/terrelsa13/MUMC/releases --> 4.1.3
https://github.com/terrelsa13/MUMC/archive/refs/heads/MUMC_v4-BETA.zip --> 4.1.4

**Comment by terrelsa13** [comment]
Apologies. I failed. Definitely a typo above. ```v4.1.14``` is ```v4.1.4```

I have updated the v4 trunk with v4.1.15-beta to prevent any future overlap or confusion.
