### ISSUE TITLE
Error in mumc

### ISSUE THREAD

**Issue by keppo070** [terrelsa13/media_cleaner#67]
Still using the 3.3.6 stable version but siderunning the 4.1.15. I had the following issue.

1 user has not seen the serie. The other does. I fails on the user who has played the serie. Before the summary

```
MUMC Version: 4.1.15-beta
Emby Version: 4.7.11.0
Python Version: 3.9.2
Time Stamp: 20230201214940
```

```
Traceback (most recent call last):
  File "/home/patrick/programmeren/python/MUMC-MUMC_v4-BETA/mumc.py", line 8540, in <module>
    episode_dict,episode_found=get_media_items('episode',config_dict,episode_dict,user_key)
  File "/home/patrick/programmeren/python/MUMC-MUMC_v4-BETA/mumc.py", line 5821, in get_media_items
    =get_playedCreatedDays_playedCreatedCounts(item,media_played_days,media_created_days,cut_off_date_played_media,cut_off_date_created_media,
  File "/home/patrick/programmeren/python/MUMC-MUMC_v4-BETA/mumc.py", line 4323, in get_playedCreatedDays_playedCreatedCounts
    if ((cut_off_date_played) > (parse(item['UserData']['LastPlayedDate']))):
  File "/usr/local/lib/python3.9/dist-packages/dateutil/parser/_parser.py", line 1368, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/dateutil/parser/_parser.py", line 643, in parse
    raise ParserError("Unknown string format: %s", timestr)
dateutil.parser._parser.ParserError: Unknown string format: Unplayed
```

Could it be something with the name of the serie ```Mo (2022)```

**Comment by terrelsa13** [comment]
There is an item for one of your users saying it has been played at least once; but somehow has no ```LastPlayedDate```.

Please set ```DEBUG=4```. Run the script. Attach ```mumc_DEBUG.log``` and reply. This will allow me to see what/why this item is and figure out a way to handle it in the script.

**Comment by keppo070** [comment]
I reimported the series and updated to the latest beta and everything seems to work now.
