### ISSUE TITLE
v4 beta impossible to set-up

### ISSUE THREAD

**Issue by Floflobel** [terrelsa13/media_cleaner#68]
Hello,

I'm trying to set up v4 but I can't. I'm stuck at the very beginning:
```
python3 mumc.py
-----------------------------------------------------------

-----------------------------------------------------------
MUMC Version: 4.1.15-beta
Emby Version: 4.8.0.21
Python Version: 3.11.1
Time Stamp: 20230207142656
-----------------------------------------------------------

-----------------------------------------------------------
Start...
Cleaning media for server at: https://domain:443/emby
-----------------------------------------------------------

Traceback (most recent call last):
  File "/opt/MUMC_v4/mumc.py", line 8441, in <module>
    ((('played_filter_movie' in config_dict) and (does_index_exist(config_dict['played_filter_movie'],0)) and (config_dict['played_filter_audiobook'][0] == -1)) or (not ('played_filter_movie' in config_dict))) and
                                                                                                               ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'played_filter_audiobook'
```

If I set "UPDATE_CONFIG=True" I get this error:
```
python3 mumc.py 
-----------------------------------------------------------
Version: 4.1.15-beta
-----------------------------------------------------------
Decide how the script will use the libraries chosen for each user.
0 - blacklist - Chosen libraries will blacklisted.
                All other libraries will be whitelisted.
1 - whitelist - Chosen libraries will whitelisted.
                All other libraries will be blacklisted.

Script previously setup using '1 - whitelist'.
Choose how the script will use the chosen libraries. (default blacklist): 1
-----------------------------------------------------------
Decide how the script will match media items to libraries.
0 - byId - Media items will be matched to libraries using 'LibraryIds'.
1 - byPath - Media items will be matched to libraries using 'Paths'.
2 - byNetworkPath - Media items will be matched to libraries using 'NetworkPaths'.
   If your libraries do not have a 'Shared Network Folder' you must filter byPath.
   If your libraries have a 'Shared Network Folder' you must filter byNetworkPath.
   Filtering byId does not have the above limitations.

Script previously setup to match media items to libraries byid.
Choose how the script will match media items to libraries. (default byId): 
-----------------------------------------------------------
Traceback (most recent call last):
  File "/opt/MUMC_v4/mumc.py", line 8421, in <module>
    edit_configuration_file(cfg,config_dict['UPDATE_CONFIG'])
  File "/opt/MUMC_v4/mumc.py", line 2470, in edit_configuration_file
    build_configuration_file(cfg,updateConfig)
  File "/opt/MUMC_v4/mumc.py", line 1515, in build_configuration_file
    user_keys_and_bllibs,user_keys_and_wllibs=get_users_and_libraries(cfg.server_url,auth_key,library_setup_behavior,updateConfig,library_matching_behavior.lower())
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/MUMC_v4/mumc.py", line 1263, in get_users_and_libraries
    bluser_keys_json_verify,bluser_names_json_verify,w,x,y,z=user_lib_builder(cfg.user_bl_libs)
                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/MUMC_v4/mumc.py", line 843, in user_lib_builder
    for keySlotLibData in currentUser[keySlots]:
                          ~~~~~~~~~~~^^^^^^^^^^
TypeError: string indices must be integers, not 'str'
```

**Comment by terrelsa13** [comment]
I'm looking at this. Should have it fixed in the next 24hrs.

**Comment by terrelsa13** [comment]
Updated the trunk. [v4.1.17](https://github.com/terrelsa13/MUMC/tree/MUMC_v4-BETA) should work.

**Comment by Floflobel** [comment]
I confirm that everything is ok. Thank you.
