### ISSUE TITLE
Errors When ```REMOVE_FILES=True```

### ISSUE THREAD

**Issue by terrelsa13** [terrelsa13/media_cleaner#69]
Media items are still deleted. The the following error occurs for every deleted media item when ```DEBUG=4```.

```python
generic exception: Traceback (most recent call last):
  File "/opt/MUMC/mumc.py", line 509, in requestURL
    appendTo_DEBUG_log("\n" + convert2json(data),4)
                              ^^^^^^^^^^^^^^^^^^
  File "/opt/MUMC/mumc.py", line 190, in convert2json
    ezjson = json.dumps(rawjson, sort_keys=False, indent=4)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/encoder.py", line 202, in encode
    chunks = list(chunks)
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/MUMC/mumc.py", line 6329, in delete_media_item
    requestURL(req, GLOBAL_DEBUG, 'delete_media_item_request', 3)
  File "/opt/MUMC/mumc.py", line 515, in requestURL
    if (err.msg == 'Unauthorized'):
        ^^^^^^^
AttributeError: 'TypeError' object has no attribute 'msg'
```

**Comment by terrelsa13** [comment]
Fixed in v4.1.18-beta
