### ISSUE TITLE
Error creating new mumc_config.yaml with Version: 5.2.0

### ISSUE THREAD

**Issue by keppo070** [terrelsa13/media_cleaner#92]
Version: 5.2.0
When creating a new mumc_config.yaml file.  Directly after <enter> when finished

```
Exception When Selecting User. Try again.

0 - Axxx -
1 - patrick -

Monitoring multiple users is possible.
When multiple users are selected; the user with the oldest last played time will determine if media can be deleted.
Select one user at a time.
Enter number of the next user to monitor; leave blank when finished:


----------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/patrick/programmeren/python/mumc5b/MUMC-MUMC-Beta/mumc_modules/mumc_config_import.py", line 87, in importConfig
    import mumc_config as cfg
ModuleNotFoundError: No module named 'mumc_config'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/patrick/programmeren/python/mumc5b/MUMC-MUMC-Beta/mumc.py", line 104, in <module>
    main()
  File "/home/patrick/programmeren/python/mumc5b/MUMC-MUMC-Beta/mumc.py", line 27, in main
    cfg,init_dict=importConfig(init_dict,cmdopt_dict)
  File "/home/patrick/programmeren/python/mumc5b/MUMC-MUMC-Beta/mumc_modules/mumc_config_import.py", line 103, in importConfig
    importHasException(init_dict,cmdopt_dict)
  File "/home/patrick/programmeren/python/mumc5b/MUMC-MUMC-Beta/mumc_modules/mumc_config_import.py", line 22, in importHasException
    build_configuration_file(init_dict)
  File "/home/patrick/programmeren/python/mumc5b/MUMC-MUMC-Beta/mumc_modules/mumc_config_builder.py", line 108, in build_configuration_file
    yaml_configurationBuilder(the_dict)
  File "/home/patrick/programmeren/python/mumc5b/MUMC-MUMC-Beta/mumc_modules/mumc_configuration_yaml.py", line 288, in yaml_configurationBuilder
    save_yaml_config(config_data,the_dict['mumc_path'] + '/' + the_dict['config_file_name_yaml'])
TypeError: unsupported operand type(s) for +: 'PosixPath' and 'str'

```

**Comment by terrelsa13** [comment]
My b. Missed a string conversion for a posixPath.
Try v5.2.1.
